name: Benchmark

inputs:
  version:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - env:
        WEBHOOKX_VERSION: ${{ inputs.version }}
      shell: bash
      run: make bench-all ARGS="--quiet"
