name: Benchmark

inputs:
  version:
    description: ''
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: make bench-all ARGS="--quiet"
      working-directory: ${{ github.action_path }}
      env:
        WEBHOOKX_VERSION: ${{ inputs.version }}
