worker_processes 1;

worker_rlimit_nofile 65535;

events {
    accept_mutex off;
    worker_connections 65535;
}

http {
    lua_package_path "/usr/local/openresty/nginx/conf/?.lua;;";
    server {
        listen 9999;
        access_log off;

        # API /
        location / {
            return 200 "ok";
        }

        # API /delay/{ms}
        location ~ ^/delay/(\d+)$ {
            content_by_lua_block {
                local ms = tonumber(ngx.var[1])
                if not ms then
                    ngx.status = 400
                    ngx.say("invalid delay")
                    return
                end

                ngx.sleep(ms / 1000)
                ngx.say("delayed ", ms, " ms")
            }
        }

        # API /status/{code}
        location ~ ^/status/(\d+)$ {
            content_by_lua_block {
                local code = tonumber(ngx.var[1])
                if not code then
                    ngx.status = 400
                    ngx.say("invalid status code")
                    return
                end

                ngx.status = code
            }
        }

        # API /latency_state
        # POST record end-to-end latency
        # DELETE reset end-to-end latency
        # GET get end-to-end latency result
        location /latency_state {
            content_by_lua_block {
                local store = require("latency")
                local cjson = require("cjson.safe")
                local method = ngx.req.get_method()

                if method == "GET" then
                    local stats = store.stats()
                    local s = 'Latency Results\n' ..
                              'total requests: ' .. (stats.count or 0) .. '\n' ..
                              'avg = ' .. string.format("%.2f", stats.avg or 0) .. 'ms \n' ..
                              'min = ' .. string.format("%.2f", stats.min or 0) .. 'ms \n' ..
                              'max = ' .. string.format("%.2f", stats.max or 0) .. 'ms \n' ..
                              'med = ' .. string.format("%.2f", stats.med or 0) .. 'ms \n' ..
                              'p90 = ' .. string.format("%.2f", stats.p90 or 0) .. 'ms \n' ..
                              'p95 = ' .. string.format("%.2f", stats.p95 or 0) .. 'ms \n' ..
                              'p99 = ' .. string.format("%.2f", stats.p99 or 0) .. 'ms \n'
                    ngx.say(s)
                    return
                end

                if method == "DELETE" then
                    store.reset()
                    ngx.say("reset")
                    return
                end

                ngx.req.read_body()
                local body = ngx.req.get_body_data()

                if not body then
                    ngx.status = 400
                    ngx.say("invalid request body")
                    return
                end

                local json = cjson.decode(body)
                if not json.timestamp then
                    ngx.status = 400
                    ngx.say("invalid timestamp")
                    return
                end

                local latency = ngx.now() * 1000 - json.timestamp
                store.add(latency)

                ngx.say("latency: ", latency, "ms")
            }
        }

        location /nginx_status {
            stub_status on;
            access_log off;
        }
    }
}
